[workspace]
members = [
  "libbud/server",
  "libbud/common",
  "libbud/client",
  "bin/server",
  "bin/client",
]

[workspace.dependencies]
bytes = "~1.4"
futures = "~0.3"
libbud-common = { version = "~0.1", path = "libbud/common" }
log = "~0.4"
once_cell = "~1.17"
roaring = "~0.10"
s2n-quic = { version = "~1.18", features = ["provider-address-token-default", "provider-tls-rustls"] }
tokio = { version = "~1.27", features = ["sync"] }
tokio-util = { version = "~0.7", features = ["codec"] }
