[workspace]
members = [
  "libbud/*",
  "server",
]

[workspace.dependencies]
anyhow = "~1.0.70"
async-trait = "0.1.68"
bytes = "~1.4.0"
clap = { version = "~4.2.2", features = ["derive", "env"] }
chrono = "~0.4.24"
rustls-pemfile = "~1.0.2"
flexi_logger = { version = "~0.25.3", features = ["compress"] }
futures = "~0.3.28"
libbud-common = { version = "~0.1.0", path = "libbud/common" }
libbud-server = { version = "~0.1.0", path = "libbud/server" }
log = "~0.4.17"
once_cell = "~1.17.1"
openssl = { version = "~0.10.50", features = ["vendored"] }
roaring = "~0.10.1"
s2n-quic = { version = "~1.18.0", features = ["provider-address-token-default", "provider-tls-rustls"] }
signal-hook-tokio = { version = "~0.3.1", features = ["futures-v0_3"] }
signal-hook = "~0.3.15"
tokio = "~1.27.0"
tokio-util = { version = "~0.7.7", features = ["codec"] }
