[package]
name = "libbud-common"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes.workspace = true
chrono.workspace = true
rustls-pemfile.workspace = true
s2n-quic.workspace = true
tokio-util.workspace = true
